# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\cmake\cmake-3.30.3-windows-x86_64\bin\cmake.exe

# The command to remove a file.
RM = C:\cmake\cmake-3.30.3-windows-x86_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\red93\Desktop\projects\image_edge_detection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\red93\Desktop\projects\image_edge_detection

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	C:\cmake\cmake-3.30.3-windows-x86_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\cmake\cmake-3.30.3-windows-x86_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\red93\Desktop\projects\image_edge_detection\CMakeFiles C:\Users\red93\Desktop\projects\image_edge_detection\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\red93\Desktop\projects\image_edge_detection\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ced

# Build rule for target.
ced: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ced
.PHONY : ced

# fast build rule for target.
ced/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/build
.PHONY : ced/fast

src/gaussian.obj: src/gaussian.cpp.obj
.PHONY : src/gaussian.obj

# target to build an object file
src/gaussian.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/gaussian.cpp.obj
.PHONY : src/gaussian.cpp.obj

src/gaussian.i: src/gaussian.cpp.i
.PHONY : src/gaussian.i

# target to preprocess a source file
src/gaussian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/gaussian.cpp.i
.PHONY : src/gaussian.cpp.i

src/gaussian.s: src/gaussian.cpp.s
.PHONY : src/gaussian.s

# target to generate assembly for a file
src/gaussian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/gaussian.cpp.s
.PHONY : src/gaussian.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nonMaxSup.obj: src/nonMaxSup.cpp.obj
.PHONY : src/nonMaxSup.obj

# target to build an object file
src/nonMaxSup.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/nonMaxSup.cpp.obj
.PHONY : src/nonMaxSup.cpp.obj

src/nonMaxSup.i: src/nonMaxSup.cpp.i
.PHONY : src/nonMaxSup.i

# target to preprocess a source file
src/nonMaxSup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/nonMaxSup.cpp.i
.PHONY : src/nonMaxSup.cpp.i

src/nonMaxSup.s: src/nonMaxSup.cpp.s
.PHONY : src/nonMaxSup.s

# target to generate assembly for a file
src/nonMaxSup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/nonMaxSup.cpp.s
.PHONY : src/nonMaxSup.cpp.s

src/sobel.obj: src/sobel.cpp.obj
.PHONY : src/sobel.obj

# target to build an object file
src/sobel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/sobel.cpp.obj
.PHONY : src/sobel.cpp.obj

src/sobel.i: src/sobel.cpp.i
.PHONY : src/sobel.i

# target to preprocess a source file
src/sobel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/sobel.cpp.i
.PHONY : src/sobel.cpp.i

src/sobel.s: src/sobel.cpp.s
.PHONY : src/sobel.s

# target to generate assembly for a file
src/sobel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ced.dir\build.make CMakeFiles/ced.dir/src/sobel.cpp.s
.PHONY : src/sobel.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... ced
	@echo ... src/gaussian.obj
	@echo ... src/gaussian.i
	@echo ... src/gaussian.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/nonMaxSup.obj
	@echo ... src/nonMaxSup.i
	@echo ... src/nonMaxSup.s
	@echo ... src/sobel.obj
	@echo ... src/sobel.i
	@echo ... src/sobel.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

